courses/urls.py
# courses/urls.py

from django.urls import path
from . import views

app_name = 'courses'

urlpatterns = [
    path('courses/', views.courses_list, name='courses_list'),
    path('permission/', views.permission, name='permission'),
    path('logout/', views.logout_view, name='logout'),
    path('dashboard/teacher/', views.teacher_dashboard, name='teacher_dashboard'),
    path('dashboard/admin/', views.admin_dashboard, name='admin_dashboard'),
    path('dashboard/student/', views.student_dashboard, name='student_dashboard'),
    path('delete/<int:course_id>/', views.delete_course, name='delete_course'),
    path('create/', views.create_course, name='create_course'),
    path('copy/', views.view_copy, name='view_copy'),
    path('download/',views.download_encrypted_file, name='download_encrypted_file')
]

secure_project/urls.py
# project/urls.py

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('courses/', include('courses.urls')),
    path('', include('accounts.urls')), 
]

courses/models.py
from django.db import models
from accounts.models import CustomUser as User

class Course(models.Model):
    name = models.CharField(max_length=100)
    teacher = models.ForeignKey(User, on_delete=models.CASCADE, related_name='courses_taught')
    students = models.ManyToManyField(User, related_name='courses_taken', blank=True)

    def __str__(self):
        return self.name
    
class Copy(models.Model):
    student = models.ForeignKey(User, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    graded = models.BooleanField(default=False)
    mark = models.CharField(null=True, max_length=2)
    mark_student = models.BinaryField(null=True, max_length=2)
    filename = models.BinaryField(null=True)
    file = models.FileField(upload_to='server_list/')

    def __str__(self):
        return f"Copy for {self.student} - Course: {self.course}"

courses/forms.py
from django import forms
from .models import Course, Copy
from accounts.models import CustomUser as User

class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ['name', 'teacher', 'students']
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        # Filter users by user type for students and teachers
        self.fields['teacher'].queryset = User.objects.filter(user_type='teacher')
        self.fields['students'].queryset = User.objects.filter(user_type='student')

class CopyForm(forms.ModelForm):
    def __init__(self, teacher, *args, **kwargs):
        super().__init__(*args, **kwargs)
        courses_taught = teacher.courses_taught.all()
        self.fields['course'].queryset = courses_taught
        self.fields['student'].queryset = User.objects.filter(courses_taken__in=courses_taught).distinct()

    class Meta:
        model = Copy
        fields = ['student', 'course', 'graded', 'mark', 'file']

courses/views.py
# courses/views.py

from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseForbidden
from django.core.files.base import ContentFile
from .forms import CourseForm, CopyForm
from .models import Copy, Course
from accounts.models import CustomUser
from utils.encryption_utils import decrypt_file, decrypt_with_private_key, encrypt_file, encrypt_with_public_key, generate_key
from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives import serialization
from django.utils.encoding import smart_str

@login_required(login_url="login")
def logout_view(request):
    logout(request)
    return redirect('home')

@login_required(login_url="login")
def courses_list(request):
    student = request.user
    courses = student.courses_taken.all()
    return render(request, 'courses/list-courses.html', {'courses': courses})

@login_required(login_url="login")
def download_encrypted_file(request):
    copies = Copy.objects.filter(course__teacher=request.user)
    
    # Initialize with default values
    decrypted_file_content = 'error to download the file'
    decrypted_file_name = 'error_filename.txt'
    
    for copy in copies:
        if copy.file:  # Check if there's a file associated with the copy
            title = str(copy.file)
            encryption_key = generate_key(request.user.username)  # Get the encryption key
            decrypted_file_name = decrypt_file(copy.filename, encryption_key)  # Decrypt the filename
            try:
                with open(title, "rb") as file:
                    binary_data = file.read()
                decrypted_file_content = decrypt_file(binary_data, encryption_key)  # Decrypt the content
            except FileNotFoundError:
                print(f"File not found at path: {title}")
            except Exception as e:
                print(f"An error occurred: {str(e)}")

    # Create an HttpResponse object
    response = HttpResponse(content_type='application/octet-stream')
    
    # Use smart_str to handle non-ASCII characters in the filename
    response['Content-Disposition'] = f'attachment; filename="{smart_str(decrypted_file_name)}"'
    
    # Write the content to the response
    response.write(decrypted_file_content)    
    return response


@login_required(login_url="login")
def teacher_dashboard(request):
    user = request.user
    if user.user_type != 'teacher':
        return HttpResponseForbidden("You don't have permission to access this page.")

    if request.method == 'POST':
        form = CopyForm(user,request.POST, request.FILES)
        if form.is_valid():
            copy = form.save(commit=False)  # Save the form data without committing to the database
            copy.teacher = user
            if copy.file:  # Check if a file is provided
                encryption_key = generate_key(request.user.username)
                encrypted_data = encrypt_file(copy.file.read(), encryption_key)
                encrypted_filename = encrypt_file(str(copy.file).encode(), encryption_key)
                copy.filename = encrypted_filename
                copy.file.save(str(encrypted_filename), ContentFile(encrypted_data), save=False)
                
                mark = form.cleaned_data.get('mark')
                username = form.cleaned_data.get('student')
                student = CustomUser.objects.get(username=username)
                if mark is not None:
                    pubkey = serialization.load_pem_public_key(student.public_key, backend=default_backend())
                    encrypted_mark_student = encrypt_with_public_key(public_key=pubkey, data=str(mark))
                    encrypted_mark = encrypt_file(str(mark).encode(), encryption_key)
                    copy.mark = encrypted_mark
                    copy.mark_student = encrypted_mark_student
            
            copy.save()
            return redirect('courses:view_copy')
    else:
        form = CopyForm(user)
    
    courses_taught = user.courses_taught.all()  # Get courses taught by the teacher
    students = CustomUser.objects.filter(courses_taken__in=courses_taught).distinct()  # Filter students who took those courses
    courses = courses_taught
    
    context = {
        'form': form,
        'courses': courses,
        'students': students,
    }
    
    return render(request, 'courses/teacher_dashboard.html', context)

@login_required(login_url="login")
def view_copy(request):
    copies = Copy.objects.filter(course__teacher=request.user)
    result = []
    for copy in copies:
        if copy.file:  # Check if there's a file associated with the copy
            student = copy.student
            course = copy.course
            encryption_key = generate_key(request.user.username)  # Get the encryption key
            decrypted_file_name = decrypt_file(copy.filename, encryption_key)  # Decrypt the content
            result.append(('Student -> '+student.get_username(),' Course -> '+course.name, 'File -> '+decrypted_file_name.decode()))
    context = {
        'decrypted_content':result
    }
    return render(request, 'courses/view-copy.html',context)

@login_required(login_url="login")
def admin_dashboard(request):
    user = request.user

    if user.user_type != 'admin':
        return HttpResponseForbidden("You don't have permission to access this page.")
    
    if request.method == 'POST':
        form = CourseForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('courses:admin_dashboard')
    else:
        form = CourseForm()

    courses = Course.objects.all()
    return render(request, 'courses/admin_dashboard.html', {'form': form, 'courses': courses})

@login_required(login_url="login")
def student_dashboard(request):
    user = request.user
    if user.user_type != 'student':
        return HttpResponseForbidden("You don't have permission to access this page.")
    return render(request, 'courses/student_dashboard.html')

@login_required(login_url="login")
def create_course(request): 
    if request.method == 'POST':
        form = CourseForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('admin_dashboard')  # Redirect to admin dashboard after creating a course
    else:
        form = CourseForm()
    return render(request, 'courses/create-course.html', {'form': form})

@login_required(login_url="login")
def view_marks(request):
    return render(request, 'courses/view-marks.html')

@login_required(login_url="login")
def permission(request):
    if request.method == 'POST':
        private_key_text = request.POST.get('private_key')  # Get the private key from the form
        if private_key_text:
            private_key = serialization.load_pem_private_key(
                private_key_text.encode(),
                password=None
            )

            graded_copies = Copy.objects.filter(graded=True, mark_student__isnull=False)
            copy_data = []
            for copy in graded_copies:
                encrypted_mark = copy.mark_student
                decrypted_mark = decrypt_with_private_key(private_key, encrypted_mark)
                copy_info = {
                    'course_name': copy.course.name,
                    'mark_student': decrypted_mark.decode(),
                }
                copy_data.append(copy_info)

            context = {
                'copy_data': copy_data,
            }
            return render(request, 'courses/view-marks.html', context)

    return render(request, 'courses/permission.html')

@login_required(login_url="login")
def delete_course(request, course_id):
    course = get_object_or_404(Course, id=course_id)
    if request.method == 'POST':
        course.delete()
        return redirect('courses:admin_dashboard')
    return render(request, 'courses/delete-course.html', {'course': course})

courses/templates/courses/admin_dashboard.html
{% extends 'courses/base.html' %}

{% block title %}Admin Dashboard{% endblock %}

{% block content %}
    <h2>Welcome, {{ user.username }} (Admin)</h2>
    <p>You have access to admin-specific features</p>
    
    <h3>Create Course:</h3>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create Course</button>
    </form>
    
    <h3>All Courses:</h3>
    <ul>
        {% for course in courses %}
            <li>
                {{ course.name }} - <a href="{% url 'courses:delete_course' course_id=course.id %}">Delete</a>
            </li>
        {% empty %}
            <li>No courses available.</li>
        {% endfor %}
    </ul>
{% endblock %}

courses/templates/courses/base.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}Default Title{% endblock %}</title>
    <!-- Add your CSS and JavaScript files here -->
</head>
<body>
    <!-- Header -->
    <header>
        <!-- Add your header content here -->
        <nav>
            <ul>
                <li><a href="{% url 'courses:logout' %}">Déconnexion</a></li>
            </ul>
        </nav>
    </header>

    <!-- Content -->
    <main>
        {% block content %}
        {% endblock %}
    </main>

    <!-- Footer -->
    <footer>
        <!-- Add your footer content here -->
        <p>&copy; 2023 My Courses. All rights reserved.</p>
    </footer>
</body>
</html>

courses/templates/courses/delete-course.html
{% extends 'courses/base.html' %}

{% block title %}Delete Course{% endblock %}

{% block content %}
    <h2>Delete Course</h2>
    <p>Are you sure you want to delete the course "{{ course.name }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Delete</button>
        <button><a style="text-decoration: none;" href="{% url 'courses:admin_dashboard' %}">Cancel</a></button>
    </form>
{% endblock %}

courses/templates/courses/list-courses.html
{% extends 'courses/base.html' %}

{% block title %}Courses List{% endblock %}

{% block content %}
    <h2>Courses List</h2>
    <ul>
        {% for copy in copies %}
            <li>
                {{ copy.course.name }}
                {% if request.user.user_type == 'student' %}
                    - <a href="{% url 'courses:view_copy' copy_id=copy.id %}">View Copy</a>
                    - <a href="{% url 'courses:view_marks' %}">View Marks</a>
                {% elif request.user.user_type == 'teacher' %}
                    - <a href="{% url 'courses:upload_encrypted_file' copy_id=copy.id %}">Upload Encrypted File</a>
                {% endif %}
            </li>
        {% endfor %}
    </ul>
{% endblock %}

courses/templates/courses/permission.html
{% extends 'courses/base.html' %}

{% block title %}Permission{% endblock %}

{% block content %}
    <h2>Enter Key Word</h2>
    <form method="post">
        {% csrf_token %}
        <textarea name="private_key" rows="5" cols="50"></textarea><br>
        <input type="submit" value="Submit">
    </form>
{% endblock %}

courses/templates/courses/student_dashboard.html
{% extends 'courses/base.html' %}

{% block title %}Student Dashboard{% endblock %}

{% block content %}
    <h2>Welcome, {{ user.username }} (Student)</h2>
    <p>You have access to student-specific features:</p>
    <ul>
        {% for course in courses %}
            <li>{{ course.name }} - {{ course.id }}</li>
        {% endfor %}
        <a href="{% url 'courses:permission' %}">View marks</a>
    </ul>
{% endblock %}

courses/templates/courses/teacher_dashboard.html
{% extends 'courses/base.html' %}

{% block title %}Teacher{% endblock %}

{% block content %}
<h2>Welcome, {{ user.username }} (Teacher)</h2>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        
        <button type="submit">Create Copy</button>
    </form>

    <h2>Followed Students:</h2>
    <ul>
        {% for student in students %}
            <li>{{ student.username }}</li>
        {% endfor %}
    </ul>
{% endblock %}

courses/templates/courses/view-copy.html
{% extends 'courses/base.html' %}

{% block title %}View Copies{% endblock %}

{% block content %}
    <h2>Your Copies</h2>
    <ul>
        {% for copy in decrypted_content %}
        <li>Copy for: {{ copy }}     
            <a href="{% url 'courses:download_encrypted_file' %}" download>Download</a>
        </li>
        {% endfor %}
    </ul>
{% endblock %}

courses/templates/courses/view-marks.html
{% extends 'courses/base.html' %}

{% block title %}View Marks{% endblock %}

{% block content %}
    <h1>Graded Copies Information</h1>
    <ul>
        {% for copy_info in copy_data %}
        <li>
            <strong>Course Name:</strong> {{ copy_info.course_name }}<br>
            <strong>Mark Student:</strong> {{ copy_info.mark_student }}
        </li>
        {% endfor %}
    </ul>
{% endblock %}